# Generated by scripts/codegen.py. Do not edit by hand.
from __future__ import annotations
import strawberry
from strawberry.scalars import JSON as JSONScalar
from datetime import datetime
from enum import Enum
from typing import NewType

IssueFilter = strawberry.scalar(NewType("IssueFilter", object), serialize=lambda v: v, parse_value=lambda v: v)

TeamFilter = strawberry.scalar(NewType("TeamFilter", object), serialize=lambda v: v, parse_value=lambda v: v)

TimelessDate = strawberry.scalar(NewType("TimelessDate", object), serialize=lambda v: v, parse_value=lambda v: v)

@strawberry.enum
class PaginationNulls(Enum):
    first = "first"
    last = "last"

@strawberry.enum
class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"

@strawberry.enum
class PaginationSortOrder(Enum):
    Ascending = "Ascending"
    Descending = "Descending"

@strawberry.enum
class SLADayCountType(Enum):
    all = "all"
    onlyBusinessDays = "onlyBusinessDays"

@strawberry.input
class AssigneeSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CommentCreateInput:
    body: strawberry.Maybe[str | None]
    body_data: strawberry.Maybe[JSONScalar | None]
    create_as_user: strawberry.Maybe[str | None]
    create_on_synced_slack_thread: strawberry.Maybe[bool | None]
    created_at: strawberry.Maybe[datetime | None]
    display_icon_url: strawberry.Maybe[str | None]
    do_not_subscribe_to_issue: strawberry.Maybe[bool | None]
    document_content_id: strawberry.Maybe[str | None]
    id: strawberry.Maybe[str | None]
    initiative_id: strawberry.Maybe[str | None]
    initiative_update_id: strawberry.Maybe[str | None]
    issue_id: strawberry.Maybe[str | None]
    parent_id: strawberry.Maybe[str | None]
    post_id: strawberry.Maybe[str | None]
    project_id: strawberry.Maybe[str | None]
    project_update_id: strawberry.Maybe[str | None]
    quoted_text: strawberry.Maybe[str | None]
    subscriber_ids: strawberry.Maybe[list[str] | None]

@strawberry.input
class CompletedAtSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CreatedAtSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CustomerCountSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CustomerImportantCountSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CustomerRevenueSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CustomerSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class CycleSort:
    current_cycle_first: strawberry.Maybe[bool | None] = False
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class DelegateSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class DueDateSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class EstimateSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class IssueCreateInput:
    assignee_id: strawberry.Maybe[str | None]
    completed_at: strawberry.Maybe[datetime | None]
    create_as_user: strawberry.Maybe[str | None]
    created_at: strawberry.Maybe[datetime | None]
    cycle_id: strawberry.Maybe[str | None]
    delegate_id: strawberry.Maybe[str | None]
    description: strawberry.Maybe[str | None]
    description_data: strawberry.Maybe[JSONScalar | None]
    display_icon_url: strawberry.Maybe[str | None]
    due_date: strawberry.Maybe[TimelessDate | None]
    estimate: strawberry.Maybe[int | None]
    id: strawberry.Maybe[str | None]
    inherits_shared_access: strawberry.Maybe[bool | None]
    label_ids: strawberry.Maybe[list[str] | None]
    last_applied_template_id: strawberry.Maybe[str | None]
    parent_id: strawberry.Maybe[str | None]
    preserve_sort_order_on_create: strawberry.Maybe[bool | None]
    priority: strawberry.Maybe[int | None]
    priority_sort_order: strawberry.Maybe[float | None]
    project_id: strawberry.Maybe[str | None]
    project_milestone_id: strawberry.Maybe[str | None]
    reference_comment_id: strawberry.Maybe[str | None]
    release_ids: strawberry.Maybe[list[str] | None]
    sla_breaches_at: strawberry.Maybe[datetime | None]
    sla_started_at: strawberry.Maybe[datetime | None]
    sla_type: strawberry.Maybe[SLADayCountType | None]
    sort_order: strawberry.Maybe[float | None]
    source_comment_id: strawberry.Maybe[str | None]
    source_pull_request_comment_id: strawberry.Maybe[str | None]
    state_id: strawberry.Maybe[str | None]
    sub_issue_sort_order: strawberry.Maybe[float | None]
    subscriber_ids: strawberry.Maybe[list[str] | None]
    team_id: str
    template_id: strawberry.Maybe[str | None]
    title: strawberry.Maybe[str | None]
    use_default_template: strawberry.Maybe[bool | None]

@strawberry.input
class IssueSortInput:
    accumulated_state_updated_at: strawberry.Maybe[TimeInStatusSort | None]
    assignee: strawberry.Maybe[AssigneeSort | None]
    completed_at: strawberry.Maybe[CompletedAtSort | None]
    created_at: strawberry.Maybe[CreatedAtSort | None]
    customer: strawberry.Maybe[CustomerSort | None]
    customer_count: strawberry.Maybe[CustomerCountSort | None]
    customer_important_count: strawberry.Maybe[CustomerImportantCountSort | None]
    customer_revenue: strawberry.Maybe[CustomerRevenueSort | None]
    cycle: strawberry.Maybe[CycleSort | None]
    delegate: strawberry.Maybe[DelegateSort | None]
    due_date: strawberry.Maybe[DueDateSort | None]
    estimate: strawberry.Maybe[EstimateSort | None]
    label: strawberry.Maybe[LabelSort | None]
    label_group: strawberry.Maybe[LabelGroupSort | None]
    link_count: strawberry.Maybe[LinkCountSort | None]
    manual: strawberry.Maybe[ManualSort | None]
    milestone: strawberry.Maybe[MilestoneSort | None]
    priority: strawberry.Maybe[PrioritySort | None]
    project: strawberry.Maybe[ProjectSort | None]
    release: strawberry.Maybe[ReleaseSort | None]
    root_issue: strawberry.Maybe[RootIssueSort | None]
    sla_status: strawberry.Maybe[SlaStatusSort | None]
    team: strawberry.Maybe[TeamSort | None]
    title: strawberry.Maybe[TitleSort | None]
    updated_at: strawberry.Maybe[UpdatedAtSort | None]
    workflow_state: strawberry.Maybe[WorkflowStateSort | None]

@strawberry.input
class IssueUpdateInput:
    added_label_ids: strawberry.Maybe[list[str] | None]
    added_release_ids: strawberry.Maybe[list[str] | None]
    assignee_id: strawberry.Maybe[str | None]
    auto_closed_by_parent_closing: strawberry.Maybe[bool | None]
    cycle_id: strawberry.Maybe[str | None]
    delegate_id: strawberry.Maybe[str | None]
    description: strawberry.Maybe[str | None]
    description_data: strawberry.Maybe[JSONScalar | None]
    due_date: strawberry.Maybe[TimelessDate | None]
    estimate: strawberry.Maybe[int | None]
    inherits_shared_access: strawberry.Maybe[bool | None]
    label_ids: strawberry.Maybe[list[str] | None]
    last_applied_template_id: strawberry.Maybe[str | None]
    parent_id: strawberry.Maybe[str | None]
    priority: strawberry.Maybe[int | None]
    priority_sort_order: strawberry.Maybe[float | None]
    project_id: strawberry.Maybe[str | None]
    project_milestone_id: strawberry.Maybe[str | None]
    release_ids: strawberry.Maybe[list[str] | None]
    removed_label_ids: strawberry.Maybe[list[str] | None]
    removed_release_ids: strawberry.Maybe[list[str] | None]
    sla_breaches_at: strawberry.Maybe[datetime | None]
    sla_started_at: strawberry.Maybe[datetime | None]
    sla_type: strawberry.Maybe[SLADayCountType | None]
    snoozed_by_id: strawberry.Maybe[str | None]
    snoozed_until_at: strawberry.Maybe[datetime | None]
    sort_order: strawberry.Maybe[float | None]
    state_id: strawberry.Maybe[str | None]
    sub_issue_sort_order: strawberry.Maybe[float | None]
    subscriber_ids: strawberry.Maybe[list[str] | None]
    team_id: strawberry.Maybe[str | None]
    title: strawberry.Maybe[str | None]
    trashed: strawberry.Maybe[bool | None]
    trusted: strawberry.Maybe[bool | None]

@strawberry.input
class LabelGroupSort:
    label_group_id: str
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class LabelSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class LinkCountSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class ManualSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class MilestoneSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class PrioritySort:
    no_priority_first: strawberry.Maybe[bool | None] = False
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]
    use_priority_sort_order_tiebreaker: strawberry.Maybe[bool | None] = True

@strawberry.input
class ProjectSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class ReleaseSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class RootIssueSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]
    sort: IssueSortInput

@strawberry.input
class SlaStatusSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class TeamSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class TimeInStatusSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class TitleSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class UpdatedAtSort:
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.input
class WorkflowStateSort:
    closed_issues_ordered_by_recency: strawberry.Maybe[bool | None] = False
    nulls: strawberry.Maybe[PaginationNulls | None] = PaginationNulls.last
    order: strawberry.Maybe[PaginationSortOrder | None]

@strawberry.type
class Comment:
    body: str
    created_at: datetime
    id: strawberry.ID
    url: str

@strawberry.type
class CommentPayload:
    comment: Comment
    success: bool

@strawberry.type
class Issue:
    assignee: User | None
    description: str | None
    id: strawberry.ID
    identifier: str
    priority: float
    state: WorkflowState
    title: str
    url: str

@strawberry.type
class IssueArchivePayload:
    success: bool

@strawberry.type
class IssueConnection:
    nodes: list[Issue]
    page_info: PageInfo

@strawberry.type
class IssuePayload:
    issue: Issue | None
    success: bool

@strawberry.type
class IssueSearchPayload:
    nodes: list[IssueSearchResult]
    page_info: PageInfo

@strawberry.type
class IssueSearchResult:
    assignee: User | None
    description: str | None
    id: strawberry.ID
    identifier: str
    priority: float
    state: WorkflowState
    title: str
    url: str

@strawberry.type
class Mutation:
    @strawberry.field
    def comment_create(self,
        input: CommentCreateInput,
    ) -> CommentPayload:
        raise NotImplementedError
    @strawberry.field
    def issue_create(self,
        input: IssueCreateInput,
    ) -> IssuePayload:
        raise NotImplementedError
    @strawberry.field
    def issue_delete(self,
        id: str,
        permanently_delete: bool | None = None,
    ) -> IssueArchivePayload:
        raise NotImplementedError
    @strawberry.field
    def issue_update(self,
        id: str,
        input: IssueUpdateInput,
    ) -> IssuePayload:
        raise NotImplementedError

@strawberry.type
class PageInfo:
    end_cursor: str | None
    has_next_page: bool
    has_previous_page: bool
    start_cursor: str | None

@strawberry.type
class Query:
    @strawberry.field
    def issue(self,
        id: str,
    ) -> Issue:
        raise NotImplementedError
    @strawberry.field
    def issues(self,
        after: str | None = None,
        before: str | None = None,
        filter: IssueFilter | None = None,
        first: int | None = None,
        include_archived: bool | None = None,
        last: int | None = None,
        order_by: PaginationOrderBy | None = None,
        sort: list[IssueSortInput] | None = None,
    ) -> IssueConnection:
        raise NotImplementedError
    @strawberry.field
    def search_issues(self,
        term: str,
        after: str | None = None,
        before: str | None = None,
        filter: IssueFilter | None = None,
        first: int | None = None,
        include_archived: bool | None = None,
        include_comments: bool | None = None,
        last: int | None = None,
        order_by: PaginationOrderBy | None = None,
        team_id: str | None = None,
    ) -> IssueSearchPayload:
        raise NotImplementedError
    @strawberry.field
    def team(self,
        id: str,
    ) -> Team:
        raise NotImplementedError
    @strawberry.field
    def teams(self,
        after: str | None = None,
        before: str | None = None,
        filter: TeamFilter | None = None,
        first: int | None = None,
        include_archived: bool | None = None,
        last: int | None = None,
        order_by: PaginationOrderBy | None = None,
    ) -> TeamConnection:
        raise NotImplementedError
    @strawberry.field
    def user(self,
        id: str,
    ) -> User:
        raise NotImplementedError
    viewer: User

@strawberry.type
class Team:
    id: strawberry.ID
    key: str
    name: str

@strawberry.type
class TeamConnection:
    nodes: list[Team]

@strawberry.type
class User:
    active: bool
    email: str
    id: strawberry.ID
    name: str

@strawberry.type
class WorkflowState:
    id: strawberry.ID
    name: str
    type: str

schema = strawberry.Schema(query=Query, mutation=Mutation, types=[AssigneeSort, CommentCreateInput, CompletedAtSort, CreatedAtSort, CustomerCountSort, CustomerImportantCountSort, CustomerRevenueSort, CustomerSort, CycleSort, DelegateSort, DueDateSort, EstimateSort, IssueCreateInput, IssueFilter, IssueSortInput, IssueUpdateInput, LabelGroupSort, LabelSort, LinkCountSort, ManualSort, MilestoneSort, PaginationNulls, PaginationOrderBy, PaginationSortOrder, PrioritySort, ProjectSort, ReleaseSort, RootIssueSort, SLADayCountType, SlaStatusSort, TeamFilter, TeamSort, TimeInStatusSort, TimelessDate, TitleSort, UpdatedAtSort, WorkflowStateSort])