# Generated by scripts/codegen.py. Do not edit by hand.
from datetime import date, datetime
from enum import Enum
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import IssueFields, IssueFieldsAssignee, IssueFieldsState

class SLADayCountType(Enum):
    all = "all"
    onlyBusinessDays = "onlyBusinessDays"

class CreateIssueResultIssueCreate(LinearModel):
    success: bool
    issue: Optional[IssueFields]

class CreateIssueResult(LinearModel):
    issue_create: CreateIssueResultIssueCreate

class IssueCreateInput(LinearModel):
    assignee_id: Optional[str] = None
    completed_at: Optional[datetime] = None
    create_as_user: Optional[str] = None
    created_at: Optional[datetime] = None
    cycle_id: Optional[str] = None
    delegate_id: Optional[str] = None
    description: Optional[str] = None
    description_data: Optional[Any] = None
    display_icon_url: Optional[str] = None
    due_date: Optional[date] = None
    estimate: Optional[int] = None
    id: Optional[str] = None
    inherits_shared_access: Optional[bool] = None
    label_ids: Optional[list[str]] = None
    last_applied_template_id: Optional[str] = None
    parent_id: Optional[str] = None
    preserve_sort_order_on_create: Optional[bool] = None
    priority: Optional[int] = None
    priority_sort_order: Optional[float] = None
    project_id: Optional[str] = None
    project_milestone_id: Optional[str] = None
    reference_comment_id: Optional[str] = None
    release_ids: Optional[list[str]] = None
    sla_breaches_at: Optional[datetime] = None
    sla_started_at: Optional[datetime] = None
    sla_type: Optional[SLADayCountType] = None
    sort_order: Optional[float] = None
    source_comment_id: Optional[str] = None
    source_pull_request_comment_id: Optional[str] = None
    state_id: Optional[str] = None
    sub_issue_sort_order: Optional[float] = None
    subscriber_ids: Optional[list[str]] = None
    team_id: str
    template_id: Optional[str] = None
    title: Optional[str] = None
    use_default_template: Optional[bool] = None

class CreateIssueVariables(LinearModel):
    input: IssueCreateInput


DOCUMENT = """\
mutation CreateIssue($input: IssueCreateInput!) {
  issueCreate(input: $input) {
    success
    issue {
      ...IssueFields
    }
  }
}

fragment IssueFields on Issue {
  id
  identifier
  title
  description
  url
  priority
  state {
    id
    name
    type
  }
  assignee {
    id
    name
    email
    active
  }
}"""
