# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import AttachmentFields


class CreateAttachmentResultAttachmentCreate(LinearModel):
    success: bool
    attachment: AttachmentFields


class CreateAttachmentResult(LinearModel):
    attachment_create: CreateAttachmentResultAttachmentCreate


class AttachmentCreateInput(LinearModel):
    comment_body: Optional[str] = None
    comment_body_data: Optional[dict[str, Any]] = None
    create_as_user: Optional[str] = None
    display_icon_url: Optional[str] = None
    group_by_source: Optional[bool] = None
    icon_url: Optional[str] = None
    id: Optional[str] = None
    issue_id: str
    metadata: Optional[dict[str, Any]] = None
    subtitle: Optional[str] = None
    title: str
    url: str


class CreateAttachmentVariables(LinearModel):
    input: AttachmentCreateInput


DOCUMENT = """\
mutation CreateAttachment($input: AttachmentCreateInput!) {
  attachmentCreate(input: $input) {
    success
    attachment {
      ...AttachmentFields
    }
  }
}

fragment AttachmentFields on Attachment {
  id
  title
  subtitle
  url
}"""
