# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    IssueRelationFields,
    IssueRelationFieldsIssue,
    IssueRelationFieldsRelatedIssue,
)


class CreateIssueRelationResultIssueRelationCreate(LinearModel):
    success: bool
    issue_relation: IssueRelationFields


class CreateIssueRelationResult(LinearModel):
    issue_relation_create: CreateIssueRelationResultIssueRelationCreate


class IssueRelationType(Enum):
    blocks = "blocks"
    duplicate = "duplicate"
    related = "related"
    similar = "similar"


class IssueRelationCreateInput(LinearModel):
    id: Optional[str] = None
    issue_id: str
    related_issue_id: str
    type: IssueRelationType


class CreateIssueRelationVariables(LinearModel):
    input: IssueRelationCreateInput


DOCUMENT = """\
mutation CreateIssueRelation($input: IssueRelationCreateInput!) {
  issueRelationCreate(input: $input) {
    success
    issueRelation {
      ...IssueRelationFields
    }
  }
}

fragment IssueRelationFields on IssueRelation {
  id
  type
  issue {
    id
    identifier
  }
  relatedIssue {
    id
    identifier
  }
}"""
