# Generated by scripts/codegen.py. Do not edit by hand.
from datetime import datetime
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import CommentFields

class CreateCommentResultCommentCreate(LinearModel):
    success: bool
    comment: CommentFields

class CreateCommentResult(LinearModel):
    comment_create: CreateCommentResultCommentCreate

class CommentCreateInput(LinearModel):
    body: Optional[str] = None
    body_data: Optional[Any] = None
    create_as_user: Optional[str] = None
    create_on_synced_slack_thread: Optional[bool] = None
    created_at: Optional[datetime] = None
    display_icon_url: Optional[str] = None
    do_not_subscribe_to_issue: Optional[bool] = None
    document_content_id: Optional[str] = None
    id: Optional[str] = None
    initiative_id: Optional[str] = None
    initiative_update_id: Optional[str] = None
    issue_id: Optional[str] = None
    parent_id: Optional[str] = None
    post_id: Optional[str] = None
    project_id: Optional[str] = None
    project_update_id: Optional[str] = None
    quoted_text: Optional[str] = None
    subscriber_ids: Optional[list[str]] = None

class CreateCommentVariables(LinearModel):
    input: CommentCreateInput


DOCUMENT = """\
mutation CreateComment($input: CommentCreateInput!) {
  commentCreate(input: $input) {
    success
    comment {
      ...CommentFields
    }
  }
}

fragment CommentFields on Comment {
  id
  body
  url
  createdAt
}"""
