# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel

class DeleteIssueResultIssueDelete(LinearModel):
    success: bool

class DeleteIssueResult(LinearModel):
    issue_delete: DeleteIssueResultIssueDelete

class DeleteIssueVariables(LinearModel):
    id: str

DOCUMENT = """\
mutation DeleteIssue($id: String!) {
  issueDelete(id: $id) {
    success
  }
}"""
