# Generated by scripts/codegen.py. Do not edit by hand.
"""Types shared by operations via GraphQL fragments."""
from datetime import datetime
from typing import Optional
from gtm_linear.models import LinearModel

class CommentFields(LinearModel):
    """GraphQL type: Comment."""
    id: str
    body: str
    url: str
    created_at: datetime

class IssueFieldsState(LinearModel):
    id: str
    name: str
    type: str

class IssueFieldsAssignee(LinearModel):
    id: str
    name: str
    email: str
    active: bool

class IssueFields(LinearModel):
    """GraphQL type: Issue."""
    id: str
    identifier: str
    title: str
    description: Optional[str]
    url: str
    priority: float
    state: IssueFieldsState
    assignee: Optional[IssueFieldsAssignee]

class TeamFields(LinearModel):
    """GraphQL type: Team."""
    id: str
    name: str
    key: str

class UserFields(LinearModel):
    """GraphQL type: User."""
    id: str
    name: str
    email: str
    active: bool

class PageInfoFields(LinearModel):
    """GraphQL type: PageInfo."""
    end_cursor: Optional[str]
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str]

class IssueSearchResultFieldsState(LinearModel):
    id: str
    name: str
    type: str

class IssueSearchResultFieldsAssignee(LinearModel):
    id: str
    name: str
    email: str
    active: bool

class IssueSearchResultFields(LinearModel):
    """GraphQL type: IssueSearchResult."""
    id: str
    identifier: str
    title: str
    description: Optional[str]
    url: str
    priority: float
    state: IssueSearchResultFieldsState
    assignee: Optional[IssueSearchResultFieldsAssignee]
