# Generated by scripts/codegen.py. Do not edit by hand.
"""Types shared by operations via GraphQL fragments."""

from datetime import datetime
from typing import Any, Optional
from gtm_linear.models import LinearModel


class CommentFieldsUser(LinearModel):
    id: str
    name: str
    email: str
    active: bool


class CommentFieldsExternalUser(LinearModel):
    id: str
    name: str
    display_name: str
    email: Optional[str]


class CommentFields(LinearModel):
    """GraphQL type: Comment."""

    id: str
    body: str
    url: str
    created_at: datetime
    user: Optional[CommentFieldsUser]
    external_user: Optional[CommentFieldsExternalUser]


class IssueFieldsState(LinearModel):
    id: str
    name: str
    type: str


class IssueFieldsAssignee(LinearModel):
    id: str
    name: str
    email: str
    active: bool


class IssueFields(LinearModel):
    """GraphQL type: Issue."""

    id: str
    identifier: str
    title: str
    description: Optional[str]
    url: str
    priority: float
    state: IssueFieldsState
    assignee: Optional[IssueFieldsAssignee]


class TeamFields(LinearModel):
    """GraphQL type: Team."""

    id: str
    name: str
    key: str


class UserFields(LinearModel):
    """GraphQL type: User."""

    id: str
    name: str
    email: str
    active: bool


class AttachmentFields(LinearModel):
    """GraphQL type: Attachment."""

    id: str
    title: str
    url: str
    source_type: Optional[str]
    source: Optional[dict[str, Any]]
    metadata: dict[str, Any]


class PageInfoFields(LinearModel):
    """GraphQL type: PageInfo."""

    end_cursor: Optional[str]
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str]


class IssueRelationFieldsRelatedIssue(LinearModel):
    id: str
    identifier: str
    title: str
    url: str


class IssueRelationFields(LinearModel):
    """GraphQL type: IssueRelation."""

    id: str
    type: str
    related_issue: IssueRelationFieldsRelatedIssue


class WorkflowStateFields(LinearModel):
    """GraphQL type: WorkflowState."""

    id: str
    name: str
    type: str
    color: str
    position: float


class IssueSearchResultFieldsState(LinearModel):
    id: str
    name: str
    type: str


class IssueSearchResultFieldsAssignee(LinearModel):
    id: str
    name: str
    email: str
    active: bool


class IssueSearchResultFields(LinearModel):
    """GraphQL type: IssueSearchResult."""

    id: str
    identifier: str
    title: str
    description: Optional[str]
    url: str
    priority: float
    state: IssueSearchResultFieldsState
    assignee: Optional[IssueSearchResultFieldsAssignee]
