# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel
from .fragments import IssueFields, IssueFieldsAssignee, IssueFieldsState

class GetIssueResult(LinearModel):
    issue: IssueFields

class GetIssueVariables(LinearModel):
    id: str


DOCUMENT = """\
query GetIssue($id: String!) {
  issue(id: $id) {
    ...IssueFields
  }
}

fragment IssueFields on Issue {
  id
  identifier
  title
  description
  url
  priority
  state {
    id
    name
    type
  }
  assignee {
    id
    name
    email
    active
  }
}"""
