# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel
from .fragments import TeamFields

class GetTeamByKeyResultTeams(LinearModel):
    nodes: list[TeamFields]

class GetTeamByKeyResult(LinearModel):
    teams: GetTeamByKeyResultTeams

class GetTeamByKeyVariables(LinearModel):
    key: str


DOCUMENT = """\
query GetTeamByKey($key: String!) {
  teams(filter: {key: {eq: $key}}, first: 1) {
    nodes {
      ...TeamFields
    }
  }
}

fragment TeamFields on Team {
  id
  name
  key
}"""
