# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel
from .fragments import TeamFields

class GetTeamResult(LinearModel):
    team: TeamFields

class GetTeamVariables(LinearModel):
    id: str


DOCUMENT = """\
query GetTeam($id: String!) {
  team(id: $id) {
    ...TeamFields
  }
}

fragment TeamFields on Team {
  id
  name
  key
}"""
