# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel
from .fragments import UserFields

class GetUserResult(LinearModel):
    user: UserFields

class GetUserVariables(LinearModel):
    id: str


DOCUMENT = """\
query GetUser($id: String!) {
  user(id: $id) {
    ...UserFields
  }
}

fragment UserFields on User {
  id
  name
  email
  active
}"""
