# Generated by scripts/codegen.py. Do not edit by hand.
from gtm_linear.models import LinearModel
from .fragments import UserFields

class GetViewerResult(LinearModel):
    viewer: UserFields


DOCUMENT = """\
query GetViewer {
  viewer {
    ...UserFields
  }
}

fragment UserFields on User {
  id
  name
  email
  active
}"""
