# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import IssueFields, IssueFieldsAssignee, IssueFieldsState, PageInfoFields

class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"

class ListIssuesResultIssues(LinearModel):
    nodes: list[IssueFields]
    page_info: PageInfoFields

class ListIssuesResult(LinearModel):
    issues: ListIssuesResultIssues

class ListIssuesVariables(LinearModel):
    filter: Optional[dict[str, Any]]
    first: int
    after: Optional[str]
    orderBy: Optional[PaginationOrderBy]
    includeArchived: bool


DOCUMENT = """\
query ListIssues($filter: IssueFilter, $first: Int!, $after: String, $orderBy: PaginationOrderBy, $includeArchived: Boolean!) {
  issues(
    filter: $filter
    first: $first
    after: $after
    orderBy: $orderBy
    includeArchived: $includeArchived
  ) {
    nodes {
      ...IssueFields
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}

fragment IssueFields on Issue {
  id
  identifier
  title
  description
  url
  priority
  state {
    id
    name
    type
  }
  assignee {
    id
    name
    email
    active
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
