# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import AttachmentFields, PageInfoFields


class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"


class ListIssueAttachmentsResultIssueAttachments(LinearModel):
    nodes: list[AttachmentFields]
    page_info: PageInfoFields


class ListIssueAttachmentsResultIssue(LinearModel):
    attachments: ListIssueAttachmentsResultIssueAttachments


class ListIssueAttachmentsResult(LinearModel):
    issue: ListIssueAttachmentsResultIssue


class ListIssueAttachmentsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    orderBy: Optional[PaginationOrderBy]
    includeArchived: bool


DOCUMENT = """\
query ListIssueAttachments($id: String!, $first: Int!, $after: String, $orderBy: PaginationOrderBy, $includeArchived: Boolean!) {
  issue(id: $id) {
    attachments(
      first: $first
      after: $after
      orderBy: $orderBy
      includeArchived: $includeArchived
    ) {
      nodes {
        ...AttachmentFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment AttachmentFields on Attachment {
  id
  title
  url
  sourceType
  source
  metadata
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
