# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    IssueRelationFields,
    IssueRelationFieldsRelatedIssue,
    PageInfoFields,
)


class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"


class ListIssueRelationsResultIssueRelations(LinearModel):
    nodes: list[IssueRelationFields]
    page_info: PageInfoFields


class ListIssueRelationsResultIssue(LinearModel):
    relations: ListIssueRelationsResultIssueRelations


class ListIssueRelationsResult(LinearModel):
    issue: ListIssueRelationsResultIssue


class ListIssueRelationsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    orderBy: Optional[PaginationOrderBy]
    includeArchived: bool


DOCUMENT = """\
query ListIssueRelations($id: String!, $first: Int!, $after: String, $orderBy: PaginationOrderBy, $includeArchived: Boolean!) {
  issue(id: $id) {
    relations(
      first: $first
      after: $after
      orderBy: $orderBy
      includeArchived: $includeArchived
    ) {
      nodes {
        ...IssueRelationFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment IssueRelationFields on IssueRelation {
  id
  type
  relatedIssue {
    id
    identifier
    title
    url
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
