# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    IssueContextRelationFields,
    IssueContextRelationFieldsIssue,
    IssueContextRelationFieldsRelatedIssue,
    PageInfoFields,
)


class ListIssueRelationsResultIssueRelations(LinearModel):
    nodes: list[IssueContextRelationFields]
    page_info: PageInfoFields


class ListIssueRelationsResultIssue(LinearModel):
    relations: ListIssueRelationsResultIssueRelations


class ListIssueRelationsResult(LinearModel):
    issue: ListIssueRelationsResultIssue


class ListIssueRelationsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    includeArchived: bool


DOCUMENT = """\
query ListIssueRelations($id: String!, $first: Int!, $after: String, $includeArchived: Boolean!) {
  issue(id: $id) {
    relations(first: $first, after: $after, includeArchived: $includeArchived) {
      nodes {
        ...IssueContextRelationFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment IssueContextRelationFields on IssueRelation {
  id
  type
  createdAt
  issue {
    id
    identifier
    title
    url
  }
  relatedIssue {
    id
    identifier
    title
    url
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
