# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    IssueContextCommentFields,
    IssueContextCommentFieldsExternalUser,
    IssueContextCommentFieldsUser,
    PageInfoFields,
)


class ListIssueCommentsResultIssueComments(LinearModel):
    nodes: list[IssueContextCommentFields]
    page_info: PageInfoFields


class ListIssueCommentsResultIssue(LinearModel):
    comments: ListIssueCommentsResultIssueComments


class ListIssueCommentsResult(LinearModel):
    issue: ListIssueCommentsResultIssue


class ListIssueCommentsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    includeArchived: bool


DOCUMENT = """\
query ListIssueComments($id: String!, $first: Int!, $after: String, $includeArchived: Boolean!) {
  issue(id: $id) {
    comments(first: $first, after: $after, includeArchived: $includeArchived) {
      nodes {
        ...IssueContextCommentFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment IssueContextCommentFields on Comment {
  id
  body
  url
  createdAt
  user {
    id
    name
    email
    active
  }
  externalUser {
    id
    displayName
    name
    email
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
