# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    IssueContextRelationFields,
    IssueContextRelationFieldsIssue,
    IssueContextRelationFieldsRelatedIssue,
    PageInfoFields,
)


class ListIssueInverseRelationsResultIssueInverseRelations(LinearModel):
    nodes: list[IssueContextRelationFields]
    page_info: PageInfoFields


class ListIssueInverseRelationsResultIssue(LinearModel):
    inverse_relations: ListIssueInverseRelationsResultIssueInverseRelations


class ListIssueInverseRelationsResult(LinearModel):
    issue: ListIssueInverseRelationsResultIssue


class ListIssueInverseRelationsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    includeArchived: bool


DOCUMENT = """\
query ListIssueInverseRelations($id: String!, $first: Int!, $after: String, $includeArchived: Boolean!) {
  issue(id: $id) {
    inverseRelations(
      first: $first
      after: $after
      includeArchived: $includeArchived
    ) {
      nodes {
        ...IssueContextRelationFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment IssueContextRelationFields on IssueRelation {
  id
  type
  createdAt
  issue {
    id
    identifier
    title
    url
  }
  relatedIssue {
    id
    identifier
    title
    url
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
