# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import IssueContextAttachmentFields, PageInfoFields


class ListIssueAttachmentsResultIssueAttachments(LinearModel):
    nodes: list[IssueContextAttachmentFields]
    page_info: PageInfoFields


class ListIssueAttachmentsResultIssue(LinearModel):
    attachments: ListIssueAttachmentsResultIssueAttachments


class ListIssueAttachmentsResult(LinearModel):
    issue: ListIssueAttachmentsResultIssue


class ListIssueAttachmentsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    includeArchived: bool


DOCUMENT = """\
query ListIssueAttachments($id: String!, $first: Int!, $after: String, $includeArchived: Boolean!) {
  issue(id: $id) {
    attachments(first: $first, after: $after, includeArchived: $includeArchived) {
      nodes {
        ...IssueContextAttachmentFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment IssueContextAttachmentFields on Attachment {
  id
  title
  url
  source
  sourceType
  metadata
  createdAt
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
