# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import PageInfoFields, WorkflowStateFields

class ListWorkflowStatesResultWorkflowStates(LinearModel):
    nodes: list[WorkflowStateFields]
    page_info: PageInfoFields

class ListWorkflowStatesResult(LinearModel):
    workflow_states: ListWorkflowStatesResultWorkflowStates

class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"

class ListWorkflowStatesVariables(LinearModel):
    filter: Optional[dict[str, Any]]
    first: int
    after: Optional[str]
    orderBy: Optional[PaginationOrderBy]
    includeArchived: bool


DOCUMENT = """\
query ListWorkflowStates($filter: WorkflowStateFilter, $first: Int!, $after: String, $orderBy: PaginationOrderBy, $includeArchived: Boolean!) {
  workflowStates(
    filter: $filter
    first: $first
    after: $after
    orderBy: $orderBy
    includeArchived: $includeArchived
  ) {
    nodes {
      ...WorkflowStateFields
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}

fragment WorkflowStateFields on WorkflowState {
  id
  name
  type
  color
  position
}"""
