# Generated by scripts/codegen.py. Do not edit by hand.
from enum import Enum
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import (
    CommentFields,
    CommentFieldsExternalUser,
    CommentFieldsUser,
    PageInfoFields,
)


class PaginationOrderBy(Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"


class ListIssueCommentsResultIssueComments(LinearModel):
    nodes: list[CommentFields]
    page_info: PageInfoFields


class ListIssueCommentsResultIssue(LinearModel):
    comments: ListIssueCommentsResultIssueComments


class ListIssueCommentsResult(LinearModel):
    issue: ListIssueCommentsResultIssue


class ListIssueCommentsVariables(LinearModel):
    id: str
    first: int
    after: Optional[str]
    orderBy: Optional[PaginationOrderBy]
    includeArchived: bool


DOCUMENT = """\
query ListIssueComments($id: String!, $first: Int!, $after: String, $orderBy: PaginationOrderBy, $includeArchived: Boolean!) {
  issue(id: $id) {
    comments(
      first: $first
      after: $after
      orderBy: $orderBy
      includeArchived: $includeArchived
    ) {
      nodes {
        ...CommentFields
      }
      pageInfo {
        ...PageInfoFields
      }
    }
  }
}

fragment CommentFields on Comment {
  id
  body
  url
  createdAt
  user {
    id
    name
    email
    active
  }
  externalUser {
    id
    name
    displayName
    email
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
