# Generated by scripts/codegen.py. Do not edit by hand.
from typing import Optional
from gtm_linear.models import LinearModel
from .fragments import IssueSearchResultFields, IssueSearchResultFieldsAssignee, IssueSearchResultFieldsState, PageInfoFields

class SearchIssuesResultSearchIssues(LinearModel):
    nodes: list[IssueSearchResultFields]
    page_info: PageInfoFields

class SearchIssuesResult(LinearModel):
    search_issues: SearchIssuesResultSearchIssues

class SearchIssuesVariables(LinearModel):
    term: str
    first: int
    after: Optional[str]


DOCUMENT = """\
query SearchIssues($term: String!, $first: Int!, $after: String) {
  searchIssues(term: $term, first: $first, after: $after) {
    nodes {
      ...IssueSearchResultFields
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}

fragment IssueSearchResultFields on IssueSearchResult {
  id
  identifier
  title
  description
  url
  priority
  state {
    id
    name
    type
  }
  assignee {
    id
    name
    email
    active
  }
}

fragment PageInfoFields on PageInfo {
  endCursor
  hasNextPage
  hasPreviousPage
  startCursor
}"""
