# Generated by scripts/codegen.py. Do not edit by hand.
from datetime import date, datetime
from enum import Enum
from typing import Any, Optional
from gtm_linear.models import LinearModel
from .fragments import IssueFields, IssueFieldsAssignee, IssueFieldsState

class SLADayCountType(Enum):
    all = "all"
    onlyBusinessDays = "onlyBusinessDays"

class UpdateIssueResultIssueUpdate(LinearModel):
    success: bool
    issue: Optional[IssueFields]

class UpdateIssueResult(LinearModel):
    issue_update: UpdateIssueResultIssueUpdate

class IssueUpdateInput(LinearModel):
    added_label_ids: Optional[list[str]] = None
    added_release_ids: Optional[list[str]] = None
    assignee_id: Optional[str] = None
    auto_closed_by_parent_closing: Optional[bool] = None
    cycle_id: Optional[str] = None
    delegate_id: Optional[str] = None
    description: Optional[str] = None
    description_data: Optional[Any] = None
    due_date: Optional[date] = None
    estimate: Optional[int] = None
    inherits_shared_access: Optional[bool] = None
    label_ids: Optional[list[str]] = None
    last_applied_template_id: Optional[str] = None
    parent_id: Optional[str] = None
    priority: Optional[int] = None
    priority_sort_order: Optional[float] = None
    project_id: Optional[str] = None
    project_milestone_id: Optional[str] = None
    release_ids: Optional[list[str]] = None
    removed_label_ids: Optional[list[str]] = None
    removed_release_ids: Optional[list[str]] = None
    sla_breaches_at: Optional[datetime] = None
    sla_started_at: Optional[datetime] = None
    sla_type: Optional[SLADayCountType] = None
    snoozed_by_id: Optional[str] = None
    snoozed_until_at: Optional[datetime] = None
    sort_order: Optional[float] = None
    state_id: Optional[str] = None
    sub_issue_sort_order: Optional[float] = None
    subscriber_ids: Optional[list[str]] = None
    team_id: Optional[str] = None
    title: Optional[str] = None
    trashed: Optional[bool] = None
    trusted: Optional[bool] = None

class UpdateIssueVariables(LinearModel):
    id: str
    input: IssueUpdateInput


DOCUMENT = """\
mutation UpdateIssue($id: String!, $input: IssueUpdateInput!) {
  issueUpdate(id: $id, input: $input) {
    success
    issue {
      ...IssueFields
    }
  }
}

fragment IssueFields on Issue {
  id
  identifier
  title
  description
  url
  priority
  state {
    id
    name
    type
  }
  assignee {
    id
    name
    email
    active
  }
}"""
