"""Generate the SDK's Pydantic models from Linear's GraphQL schema.

The pipeline, and why it has this shape:

  1. Validate every ``operations/*.graphql`` against the *full* pinned SDL with
     graphql-core. This is the real correctness gate; strawberry's own checking
     is an assert with an unhelpful message.
  2. Prune the schema down to only what the operations touch. Pruning by entity
     closure instead would drag in ~548 types, because Linear's schema is densely
     self-referential (Issue -> Team -> IssueConnection -> Issue). Operation-driven
     pruning keeps ~16, which is both faster and sidesteps most of the codegen bugs
     below, since it never reaches the exotic corners of the schema.
  3. ``strawberry schema-codegen`` turns the pruned SDL into Strawberry types plus a
     ``strawberry.Schema``, which is the input format stage 4 requires.
  4. ``strawberry codegen`` walks each operation against that schema and emits result
     and variable models, via the PydanticPlugin.
  5. ``ruff format`` (pinned in the dev group) normalises the emitted Python, so a
     regeneration is byte-stable and `trunk check` has nothing left to reformat.

``strawberry schema-codegen`` is experimental and mis-handles several constructs that
appear in a production schema. Each is worked around below and tagged BUG-n:

  BUG-1  `directive @foo on ...` raises NotImplementedError.
  BUG-2  Descriptions are not quote-escaped, so an apostrophe emits invalid Python.
  BUG-3  Enum values that are Python keywords emit `continue = "continue"`.
  BUG-4  The `JSON` scalar is emitted as `strawberry.JSON`, which does not exist.
  BUG-5  Definitions are emitted in SDL order, so a default can precede its enum.
  BUG-6  Field arguments are dropped, leaving input types unreachable from the
         schema, which makes stage 4 fail on every mutation.
  BUG-7  Root fields are emitted as class attributes with their arguments dropped;
         the Query/Mutation classes are rebuilt as resolvers.
  BUG-8  Custom scalars are emitted as ``X = strawberry.scalar(NewType(...))``, the
         class form strawberry deprecates; rewritten to plain NewType aliases whose
         definitions are registered through ``StrawberryConfig.scalar_map``.

Run `uv run python scripts/codegen.py` to regenerate, or `--check` to verify the
committed output is current (used by CI and tests/test_codegen_is_current.py).
"""

from __future__ import annotations

import argparse
import ast
import filecmp
import keyword
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import graphql.language.ast as gql_ast
from graphql import (
    GraphQLEnumType,
    GraphQLInputObjectType,
    GraphQLList,
    GraphQLNamedType,
    GraphQLNonNull,
    GraphQLObjectType,
    GraphQLScalarType,
    GraphQLSchema,
    TypeInfo,
    TypeInfoVisitor,
    Visitor,
    build_schema,
    parse,
    print_ast,
    print_type,
    validate,
    visit,
)

if TYPE_CHECKING:
    from collections.abc import Callable

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
SCHEMA_FILE = REPO_ROOT / "schema" / "linear.graphql"
OPERATIONS_DIR = REPO_ROOT / "operations"
FRAGMENTS_FILE = OPERATIONS_DIR / "_fragments.graphql"
GENERATED_DIR = REPO_ROOT / "gtm_linear" / "_generated"
SCHEMA_MODULE = REPO_ROOT / "gtm_linear" / "_schema.py"

BUILTIN_SCALARS = {"String", "Int", "Float", "Boolean", "ID"}

# Input types emitted as opaque scalars instead of being expanded.
#
# Linear's filter inputs are enormous and deeply self-referential — `IssueFilter`
# alone pulls in ~150 types and nests far enough that building the Strawberry schema
# overflows the default recursion limit. Expanding them would make gtm_linear/_schema.py
# both huge and un-importable without raising sys.setrecursionlimit, which is not an
# acceptable thing to ask of anyone using the [strawberry] extra.
#
# Correctness is unaffected: stage 1 still validates every operation, filter variable
# included, against the *full* schema. Only the generated Python view is coarsened —
# callers pass filters as plain dicts, which Linear validates server-side.
OPAQUE_INPUTS = {"IssueFilter", "TeamFilter", "WorkflowStateFilter"}

GENERATED_HEADER = "# Generated by scripts/codegen.py. Do not edit by hand.\n"

# Names the generated code may reference, and where each comes from. Used to rebuild
# a module's import block after classes are moved between modules by _hoist_fragments.
KNOWN_IMPORTS = {
    "Any": "typing",
    "Optional": "typing",
    "List": "typing",
    "datetime": "datetime",
    "date": "datetime",
    "time": "datetime",
    "Decimal": "decimal",
    "UUID": "uuid",
    "Enum": "enum",
}


def _import_block(body: str) -> str:
    """Emit exactly the imports `body` references, grouped by module."""
    by_module: dict[str, set[str]] = {}
    for name, module in KNOWN_IMPORTS.items():
        if re.search(rf"\b{name}\b", body):
            by_module.setdefault(module, set()).add(name)
    return "".join(
        f"from {module} import {', '.join(sorted(names))}\n"
        for module, names in sorted(by_module.items())
    )


def _unwrap(type_: object) -> GraphQLNamedType | None:
    """Strip ``NonNull``/``List`` wrappers, returning the underlying named type.

    ``None`` means the input was no named type at all (including ``None``
    itself) — graphql-core never produces that for the values passed here. The
    two callers disagree on purpose: ``_Collector.enter_field`` treats it as a
    schema/operation disagreement and raises, while ``close_over_input``
    silently skips it (nothing to close over either way).
    """
    while isinstance(type_, (GraphQLNonNull, GraphQLList)):
        type_ = type_.of_type
    return type_ if isinstance(type_, GraphQLNamedType) else None


def _operation_paths() -> list[Path]:
    """Operation documents, excluding `_`-prefixed helper files like _fragments."""
    return sorted(
        p for p in OPERATIONS_DIR.glob("*.graphql") if not p.name.startswith("_")
    )


def _fragment_definitions() -> dict[str, gql_ast.FragmentDefinitionNode]:
    if not FRAGMENTS_FILE.exists():
        return {}
    document = parse(FRAGMENTS_FILE.read_text())
    return {
        d.name.value: d
        for d in document.definitions
        if isinstance(d, gql_ast.FragmentDefinitionNode)
    }


def _spread_names(node: object, found: set[str]) -> None:
    if isinstance(node, gql_ast.FragmentSpreadNode):
        found.add(node.name.value)
    if isinstance(node, gql_ast.Node):
        for key in node.keys:
            _spread_names(getattr(node, key, None), found)
    elif isinstance(node, (list, tuple)):
        for item in node:
            _spread_names(item, found)


def _rebuild(
    node: object,
    overrides: Callable[[gql_ast.Node], dict[str, object]],
) -> object:
    """Rebuild an AST tree with per-node field replacements, bottom-up.

    graphql-core 3.3 freezes its AST dataclasses, so parsed documents cannot be
    edited in place — sanitized copies are constructed node by node and spliced
    into rebuilt parents. Subtrees the overrides leave untouched are shared
    as-is, so a transformation that changes nothing returns the original node.

    Every ``key`` is passed to the constructor explicitly: pre-3.3 nodes take a
    generic ``**kwargs`` init that defaults missing keys to ``None``, so a
    partial copy would silently drop fields. ``loc`` is carried through, though
    nothing downstream of this reads it.
    """
    if isinstance(node, gql_ast.Node):
        fields: dict[str, object] = overrides(node)
        changed = bool(fields)
        for key in node.keys:
            child = getattr(node, key, None)
            rebuilt = _rebuild(child, overrides)
            if rebuilt is not child:
                changed = True
            fields.setdefault(key, rebuilt)
        # graphql-core 3.3 gives Node a typed __init__ (loc: Location | None
        # etc.) instead of the pre-3.3 generic **kwargs, so the unpacked
        # values need to flow through as Any to satisfy it. The values are
        # correct by construction: each came off a real node of this class.
        return type(node)(**cast("dict[str, Any]", fields)) if changed else node
    if isinstance(node, (list, tuple)):
        items = [_rebuild(item, overrides) for item in node]
        if all(new is old for new, old in zip(items, node, strict=True)):
            return node
        return type(node)(items)
    return node


def _compose(path: Path, fragments: dict[str, gql_ast.FragmentDefinitionNode]) -> str:
    """Inline the fragments an operation references, transitively.

    Only referenced fragments are spliced in: GraphQL validation rejects a document
    containing a fragment that is never used, so dumping the whole shared file into
    every operation would fail.
    """
    document = parse(path.read_text())

    needed: set[str] = set()
    _spread_names(document, needed)
    pending = list(needed)
    while pending:
        name = pending.pop()
        definition = fragments.get(name)
        if definition is None:
            msg = f"{path.name} references unknown fragment '{name}'"
            raise SystemExit(msg)
        nested: set[str] = set()
        _spread_names(definition, nested)
        for child in nested - needed:
            needed.add(child)
            pending.append(child)

    # Splice the fragments in as a new document: graphql-core 3.3 freezes the
    # AST dataclasses, so `document.definitions = ...` would raise
    # FrozenInstanceError. `loc` is dropped, which print_ast never reads.
    document = gql_ast.DocumentNode(
        definitions=(
            *document.definitions,
            *(fragments[name] for name in sorted(needed)),
        ),
    )
    return print_ast(document)


def _collect(
    schema: GraphQLSchema,
    operations: list[tuple[str, str]],
) -> tuple[dict[str, set[str]], set[str], set[str]]:
    """Return the object fields, whole types, and opaque inputs the operations touch."""
    touched: dict[str, set[str]] = {}
    whole: set[str] = set()
    opaque: set[str] = set()

    def close_over_input(type_: object, seen: set[str]) -> None:
        type_ = _unwrap(type_)
        if type_ is None:
            return
        name = type_.name
        if name in seen:
            return
        seen.add(name)
        if name in OPAQUE_INPUTS:
            opaque.add(name)
            return
        if isinstance(type_, GraphQLInputObjectType):
            whole.add(name)
            for field in type_.fields.values():
                close_over_input(field.type, seen)
        elif isinstance(type_, (GraphQLEnumType, GraphQLScalarType)):
            whole.add(name)

    for name, text in operations:
        document = parse(text)
        errors = validate(schema, document)
        if errors:
            messages = "\n".join(f"    {e.message}" for e in errors)
            msg = f"{name} does not validate against the schema:\n{messages}"
            raise SystemExit(msg)

        type_info = TypeInfo(schema)

        # _Collector takes type_info via its constructor so the binding is
        # explicit (ruff B023 also rejects closures over loop variables); it is
        # created and consumed within a single iteration, so lifetime is not
        # the concern. super().__init__() is required: graphql-core's Visitor
        # builds its enter_leave_map there.
        class _Collector(Visitor):
            def __init__(self, type_info: TypeInfo) -> None:
                """Bind the per-document TypeInfo this collector walks with."""
                super().__init__()  # Visitor.__init__ builds enter_leave_map
                self._type_info = type_info

            def enter_field(self, node: gql_ast.FieldNode, *_: object) -> None:
                parent = _unwrap(self._type_info.get_parent_type())
                field_type = _unwrap(self._type_info.get_type())
                if parent is None or field_type is None:
                    msg = f"field {node.name.value} has no named type in the schema"
                    raise SystemExit(msg)
                touched.setdefault(parent.name, set()).add(node.name.value)
                if isinstance(field_type, (GraphQLEnumType, GraphQLScalarType)):
                    whole.add(field_type.name)

                # The pruned SDL re-emits each kept field with its full argument
                # list (the BUG-6 workaround), so every argument type must be
                # carried along or the pruned schema will not build.
                field_def = getattr(parent, "fields", {}).get(node.name.value)
                if field_def is not None:
                    for argument in field_def.args.values():
                        close_over_input(argument.type, set())

        visit(document, TypeInfoVisitor(type_info, _Collector(type_info)))

        for definition in document.definitions:
            for variable in getattr(definition, "variable_definitions", None) or []:
                node = variable.type
                while hasattr(node, "type"):
                    node = node.type
                resolved = schema.get_type(node.name.value)
                if resolved is not None:
                    close_over_input(resolved, set())

    return touched, whole, opaque


def _prune(
    schema: GraphQLSchema,
    touched: dict[str, set[str]],
    whole: set[str],
    opaque: set[str],
) -> str:
    """Emit a minimal standalone SDL covering exactly what the operations need."""
    chunks: list[str] = []
    for name in sorted(opaque):
        chunks.append(f"scalar {name}")
    for name in sorted(whole):
        if name in BUILTIN_SCALARS or name.startswith("__") or name in opaque:
            continue
        type_ = schema.get_type(name)
        if type_ is not None:
            chunks.append(print_type(type_))

    for name, fields in sorted(touched.items()):
        type_ = schema.get_type(name)
        if not isinstance(type_, GraphQLObjectType):
            continue
        lines = []
        for field_name in sorted(fields):
            field = type_.fields[field_name]
            # BUG-6: arguments are dropped by schema-codegen, but they must be
            # present here so input types are reachable and get registered.
            args = ", ".join(f"{n}: {a.type}" for n, a in field.args.items())
            suffix = f"({args})" if args else ""
            lines.append(f"  {field_name}{suffix}: {field.type}")
        body = "\n".join(lines)
        chunks.append(f"type {name} {{\n{body}\n}}")

    sdl = "\n\n".join(chunks)
    build_schema(sdl)  # fail loudly here rather than deep inside strawberry
    return sdl


def _sanitize_sdl(sdl: str) -> str:
    """Strip constructs that break `strawberry schema-codegen`."""
    document = parse(sdl)
    definitions = [
        d
        for d in document.definitions
        if not isinstance(d, gql_ast.DirectiveDefinitionNode)  # BUG-1
    ]

    renamed: list[str] = []

    def overrides(node: gql_ast.Node) -> dict[str, object]:
        fields: dict[str, object] = {}
        # BUG-2: descriptions are not quote-escaped, so an apostrophe in
        # Linear's docs would emit invalid Python. Drop them everywhere.
        if getattr(node, "description", None) is not None:
            fields["description"] = None
        # BUG-3: enum values that are Python keywords emit `continue = "continue"`.
        # Independent of BUG-2: a keyword value may also carry a description.
        if isinstance(node, gql_ast.EnumValueDefinitionNode) and keyword.iskeyword(
            node.name.value,
        ):
            renamed.append(node.name.value)
            fields["name"] = gql_ast.NameNode(value=f"{node.name.value}_")
        return fields

    # Sanitize by rebuilding: graphql-core 3.3 freezes the AST dataclasses, so
    # the scrub and the keyword rename cannot mutate the parsed nodes in place.
    # _rebuild returns the same node class it is given, so the list stays
    # definition-shaped; the cast carries that knowledge into the annotation.
    definitions = [
        cast("gql_ast.DefinitionNode", _rebuild(d, overrides)) for d in definitions
    ]

    if renamed:
        print(f"  sanitized python-keyword enum values: {renamed}")

    # BUG-5: schema-codegen emits definitions in SDL order. Field *annotations* are
    # lazy (the output carries `from __future__ import annotations`), but default
    # values are evaluated at class-creation time, and Linear's sort inputs default
    # to enum members (`nulls: ... = PaginationNulls.last`). Emitting scalars and
    # enums first is therefore sufficient: nothing else can appear in a default.
    # Annotated against the AST base class so the `type(d)` lookup below accepts
    # every definition kind without pyright narrowing complaints.
    order: dict[type[gql_ast.Node], int] = {
        gql_ast.ScalarTypeDefinitionNode: 0,
        gql_ast.EnumTypeDefinitionNode: 1,
        gql_ast.InputObjectTypeDefinitionNode: 2,
        gql_ast.InterfaceTypeDefinitionNode: 3,
        gql_ast.UnionTypeDefinitionNode: 4,
    }
    definitions.sort(key=lambda d: order.get(type(d), 5))

    document = gql_ast.DocumentNode(definitions=tuple(definitions))
    return print_ast(document)


def _migrate_scalar_definitions(source: str) -> tuple[str, list[tuple[str, str]]]:
    """Rewrite schema-codegen's deprecated scalar class form (BUG-8).

    schema-codegen emits ``X = strawberry.scalar(NewType("X", object), **kwargs)``
    — the class form strawberry deprecates in favour of ``StrawberryConfig
    .scalar_map``. Each assignment becomes a plain ``NewType`` alias, and the
    kwargs are returned as ``(name, kwargs)`` pairs so the caller can register
    ``strawberry.scalar(name=..., **kwargs)`` definitions in the schema config,
    keyed by those aliases. Fails loudly on an emission the rewrite does not
    recognise, rather than silently shipping the form strawberry will remove.
    """
    found: list[tuple[str, str]] = []

    def unwrap(match: re.Match[str]) -> str:
        name = match["name"]
        kwargs = match["kwargs"] or ""
        if re.search(r"\bname=", kwargs):
            msg = (
                f"schema-codegen emitted a `name=` kwarg for scalar {name}; "
                "the scalar_map entry would duplicate it"
            )
            raise SystemExit(msg)
        found.append((name, kwargs))
        return f'{name} = NewType("{name}", object)'

    # The `(?P=name)` backreference requires the assignment target to match
    # the NewType's own name: if they ever diverge, the rewrite declines, the
    # class form survives, and the drift guard below fails the run rather than
    # silently renaming the scalar in the generated schema.
    source = re.sub(
        r'^(?P<name>\w+) = strawberry\.scalar\(NewType\("(?P=name)", object\)'
        r"(?:, (?P<kwargs>.*))?\)$",
        unwrap,
        source,
        flags=re.MULTILINE,
    )
    # Whitespace-tolerant on purpose: a future schema-codegen that wraps the
    # call across lines defeats the one-line rewrite above, and this guard is
    # what turns that drift into a loud failure instead of a silent miss.
    if re.search(r"strawberry\.scalar\(\s*NewType", source):
        msg = (
            "schema-codegen emitted a strawberry.scalar() form the scalar "
            "migration does not recognise; update _migrate_scalar_definitions"
        )
        raise SystemExit(msg)
    return source, found


def _patch_schema_module(path: Path) -> None:
    """Fix defects in schema-codegen's output that we cannot avoid upstream."""
    source = path.read_text()

    # BUG-4: `strawberry.JSON` is not a real attribute; the scalar lives elsewhere.
    if "strawberry.JSON" in source:
        source = source.replace("strawberry.JSON", "JSONScalar")
        source = re.sub(
            r"^(import strawberry\n)",
            r"\1from strawberry.scalars import JSON as JSONScalar\n",
            source,
            count=1,
            flags=re.MULTILINE,
        )

    # BUG-8: custom scalars use the deprecated `strawberry.scalar(cls)` class form,
    # which strawberry will remove. Unwrap them to NewType aliases here; their
    # definitions are registered through StrawberryConfig.scalar_map below, the
    # supported replacement.
    source, scalars = _migrate_scalar_definitions(source)
    if scalars:
        source, imported = re.subn(
            r"^(import strawberry\n)",
            r"\1from strawberry.schema.config import StrawberryConfig\n",
            source,
            count=1,
            flags=re.MULTILINE,
        )
        if not imported:
            msg = (
                "no `import strawberry` line to hang the StrawberryConfig import "
                "on; update _patch_schema_module"
            )
            raise SystemExit(msg)

    # BUG-6: input types are unreachable because field arguments were dropped, so
    # register them explicitly or `strawberry codegen` cannot resolve variables.
    # Custom scalars need the same treatment: an opaque filter (see OPAQUE_INPUTS)
    # appears only as a variable type, which is exactly the unreachable case.
    # Scalar names come from the migration above, not a re-scan of the source: a
    # NewType line the migration did not produce would land in types=[...] with
    # no scalar_map entry and die with an opaque strawberry error.
    registered = re.findall(r"@strawberry\.input(?:\([^)]*\))?\s*\nclass (\w+)", source)
    registered += [name for name, _ in scalars]
    registered += re.findall(r"@strawberry\.enum(?:\([^)]*\))?\s*\nclass (\w+)", source)
    if registered:
        config = ""
        if scalars:
            # Keyed by the NewType aliases: strawberry resolves an annotation to
            # that object, then finds its definition through this map.
            def entry(name: str, kwargs: str) -> str:
                extra = f", {kwargs}" if kwargs else ""
                return f'{name}: strawberry.scalar(name="{name}"{extra})'

            entries = ",\n".join(
                entry(name, kwargs) for name, kwargs in sorted(scalars)
            )
            config = f"config=StrawberryConfig(scalar_map={{{entries}}}), "
        names = ", ".join(sorted(set(registered)))
        # The char class excludes newlines on purpose: a wrapped Schema() call
        # must MISS here and trip the guard below, not match across lines and
        # corrupt the rewrite into unparseable Python.

        def rewrite(match: re.Match[str]) -> str:
            # Appending our config= next to an upstream one would be a
            # duplicate keyword argument; fail loudly at generation time.
            if config and re.search(r"\bconfig=", match.group(1)):
                msg = (
                    "schema-codegen now emits its own config= kwarg; "
                    "update _patch_schema_module"
                )
                raise SystemExit(msg)
            return (
                f"schema = strawberry.Schema({match.group(1)}, {config}types=[{names}])"
            )

        source, patched = re.subn(
            r"^schema = strawberry\.Schema\(([^)\n]*)\)\s*$",
            rewrite,
            source,
            flags=re.MULTILINE,
        )
        if not patched:
            msg = (
                "schema-codegen no longer emits a one-line strawberry.Schema() "
                "call to hang the types/config on; update _patch_schema_module"
            )
            raise SystemExit(msg)

    # BUG-7: schema-codegen emits root fields as class attributes and drops their
    # arguments. Rebuild the Query and Mutation classes as Strawberry resolvers so
    # the shipped schema remains a faithful mirror of the pruned SDL. Resolver
    # bodies are intentionally unimplemented: this module describes the schema for
    # callers who provide their own resolvers.
    source = _restore_root_arguments(source, path.parent / "pruned.graphql")

    source = GENERATED_HEADER + source
    ast.parse(source)  # never emit Python that does not parse
    path.write_text(source)


def _python_name(name: str) -> str:
    """Convert a GraphQL camelCase name to the generated Python spelling."""
    converted = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    return f"{converted}_" if keyword.iskeyword(converted) else converted


def _python_type(type_: object, *, nullable: bool = True) -> str:
    """Render a GraphQL type reference as a Python annotation."""
    if isinstance(type_, GraphQLNonNull):
        return _python_type(type_.of_type, nullable=False)
    if isinstance(type_, GraphQLList):
        rendered = f"list[{_python_type(type_.of_type)}]"
    else:
        name = getattr(type_, "name", "Any")
        rendered = {
            "Boolean": "bool",
            "DateTime": "datetime",
            "Float": "float",
            "ID": "strawberry.ID",
            "Int": "int",
            "String": "str",
        }.get(name, name)
    return f"{rendered} | None" if nullable else rendered


def _restore_root_arguments(source: str, sdl_path: Path) -> str:
    """Restore Query/Mutation arguments omitted by Strawberry schema-codegen."""
    schema = build_schema(sdl_path.read_text())
    tree = ast.parse(source)
    replacements: list[tuple[int, int, str]] = []

    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or node.name not in {"Query", "Mutation"}:
            continue
        root = schema.get_type(node.name)
        if not isinstance(root, GraphQLObjectType):
            continue

        lines = ["@strawberry.type", f"class {node.name}:"]
        for field_name, field in root.fields.items():
            python_field = _python_name(field_name)
            return_type = _python_type(field.type)
            if not field.args:
                lines.append(f"    {python_field}: {return_type}")
                continue

            required = [
                (name, argument)
                for name, argument in field.args.items()
                if isinstance(argument.type, GraphQLNonNull)
            ]
            optional = [
                (name, argument)
                for name, argument in field.args.items()
                if not isinstance(argument.type, GraphQLNonNull)
            ]
            lines.extend(
                [
                    "    @strawberry.field",
                    f"    def {python_field}(self,",
                ],
            )
            for argument_name, argument in [*required, *optional]:
                default = "" if isinstance(argument.type, GraphQLNonNull) else " = None"
                lines.append(
                    f"        {_python_name(argument_name)}: {_python_type(argument.type)}{default},",
                )
            lines.extend(
                [
                    f"    ) -> {return_type}:",
                    "        raise NotImplementedError",
                ],
            )

        start = node.lineno - 1
        if start > 0 and source.splitlines()[start - 1].strip() == "@strawberry.type":
            start -= 1
        # `end_lineno` is Optional on the AST node, but a node parsed from real
        # source always carries it; refuse to splice a class we cannot delimit.
        end = node.end_lineno
        if end is None:
            msg = f"class {node.name} has no end_lineno; refusing to splice"
            raise SystemExit(msg)
        replacements.append((start, end, "\n".join(lines) + "\n"))

    lines = source.splitlines(keepends=True)
    for start, end, replacement in reversed(replacements):
        lines[start:end] = [replacement]
    result = "".join(lines)
    ast.parse(result)
    return result


def _hoist_fragments(generated_out: Path, fragment_names: set[str]) -> list[str]:
    """Move fragment-derived classes into a single shared module.

    strawberry codegen processes each operation independently, so a fragment used by
    five operations yields five structurally identical but distinct classes. That
    would give the SDK five different `IssueFields` types and make `isinstance`
    useless across methods. The classes are byte-identical by construction (same
    fragment), so hoisting them into `_generated/fragments.py` is safe and gives the
    public API exactly one type per fragment.
    """
    shared: dict[str, str] = {}
    order: list[str] = []
    # fragments.py is this function's own output; re-reading it on a later run would
    # compare a hoisted class against itself and look like a conflict.
    modules = sorted(
        p for p in generated_out.glob("*.py") if p.stem not in {"__init__", "fragments"}
    )

    def is_fragment_class(name: str) -> bool:
        return any(name.startswith(f) for f in fragment_names)

    for path in modules:
        source = path.read_text()
        lines = source.splitlines(keepends=True)
        tree = ast.parse(source)
        keep_spans: list[tuple[int, int]] = []
        used: list[str] = []

        for node in tree.body:
            if not isinstance(node, ast.ClassDef) or not is_fragment_class(node.name):
                continue
            start = node.lineno - 1
            # As above: parsed ClassDef nodes always carry end_lineno; treat a
            # missing one as a hard error rather than hoisting a bogus span.
            end = node.end_lineno
            if end is None:
                msg = f"class {node.name} has no end_lineno; refusing to hoist"
                raise SystemExit(msg)
            block = "".join(lines[start:end]).rstrip() + "\n"
            if node.name in shared:
                if shared[node.name] != block:
                    msg = f"fragment class {node.name} differs between operations"
                    raise SystemExit(msg)
            else:
                shared[node.name] = block
                order.append(node.name)
            keep_spans.append((start, end))
            used.append(node.name)

        if not used:
            continue

        # Rebuild the module from its remaining class bodies so the import block
        # reflects what is actually left after the fragment classes moved out.
        drop = {i for start, end in keep_spans for i in range(start, end)}
        kept_lines = [
            line
            for i, line in enumerate(lines)
            if i not in drop and not line.startswith(("from ", "import ", "#"))
        ]
        body = re.sub(r"\n{3,}", "\n\n", "".join(kept_lines)).strip()
        text = (
            GENERATED_HEADER
            + _import_block(body)
            + "from gtm_linear.models import LinearModel\n"
            + f"from .fragments import {', '.join(sorted(used))}\n"
            + "\n"
            + body
            + "\n"
        )
        ast.parse(text)
        path.write_text(text)

    if shared:
        body = "\n".join(shared[name] for name in order)
        text = (
            GENERATED_HEADER
            + '"""Types shared by operations via GraphQL fragments."""\n'
            + _import_block(body)
            + "from gtm_linear.models import LinearModel\n"
            + "\n"
            + body
        )
        ast.parse(text)
        (generated_out / "fragments.py").write_text(text)

    return order


def _run(cmd: list[str], extra_path: Path | None = None) -> None:
    env = os.environ.copy()
    if extra_path is not None:
        # strawberry's --app-dir only takes one directory, but the run needs two on
        # the path: the temp dir holding the generated schema module, and the repo
        # root for scripts.pydantic_plugin.
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = os.pathsep.join(filter(None, [str(extra_path), existing]))
    result = subprocess.run(  # noqa: S603
        cmd,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    if result.returncode != 0:
        msg = f"command failed: {' '.join(cmd)}\n{result.stdout}\n{result.stderr}"
        raise SystemExit(msg)


def _ruff_format(paths: list[Path]) -> None:
    """Run ``ruff format`` over generated files so codegen and trunk agree on bytes.

    The formatter is the last pipeline stage on purpose: strawberry emits valid but
    unformatted Python, and `trunk check` (which enables `ruff format`) would otherwise
    rewrite the committed output on the next run, making ``--check`` fail for reasons
    unrelated to the schema.
    """
    if not paths:
        return
    _run([sys.executable, "-m", "ruff", "format", *map(str, paths)])


def _embed_documents(
    generated_out: Path,
    composed: list[tuple[str, str]],
) -> list[str]:
    """Append each operation's composed GraphQL to its generated module.

    Embedding the document keeps the SDK from parsing ``.graphql`` files at
    runtime — graphql-core stays a build-time dependency. Also stamps the
    generated header and re-validates that the result still parses.
    """
    documents = {Path(name).stem: text for name, text in composed}
    modules = sorted(
        p.stem
        for p in generated_out.glob("*.py")
        if p.stem not in {"__init__", "fragments"}
    )
    for module in modules:
        path = generated_out / f"{module}.py"
        text = path.read_text()
        if not text.startswith(GENERATED_HEADER):
            text = GENERATED_HEADER + text
        document = documents[module]
        if '"""' in document:
            msg = f"{module}: document contains a triple quote and cannot be embedded"
            raise SystemExit(msg)
        text += f'\n\nDOCUMENT = """\\\n{document}"""\n'
        path.write_text(text)
        ast.parse(text)
    return modules


def generate(schema_out: Path, generated_out: Path) -> None:
    """Run the full pipeline, writing the schema module and generated models."""
    paths = _operation_paths()
    if not paths:
        msg = f"no operations found in {OPERATIONS_DIR}"
        raise SystemExit(msg)

    fragments = _fragment_definitions()
    composed = [(p.name, _compose(p, fragments)) for p in paths]

    schema = build_schema(SCHEMA_FILE.read_text())
    print(f"validating {len(composed)} operation(s) against the pinned schema")
    touched, whole, opaque = _collect(schema, composed)

    sdl = _sanitize_sdl(_prune(schema, touched, whole, opaque))
    print(
        f"  pruned to {len(touched) + len(whole) + len(opaque)} types "
        f"({len(opaque)} opaque), {len(sdl)} bytes",
    )

    with tempfile.TemporaryDirectory() as tmp:
        pruned_path = Path(tmp) / "pruned.graphql"
        pruned_path.write_text(sdl)
        # The schema module is generated into the temp dir and imported from there,
        # not from inside the package. Importing it as gtm_linear._schema would drag
        # in gtm_linear/__init__.py, which imports the very modules this run is about
        # to produce — so a clean checkout could never bootstrap. It is copied into
        # the package at the end, purely to be shipped with the [strawberry] extra.
        tmp_schema = Path(tmp) / "_linear_schema.py"
        _run(
            [
                sys.executable,
                "-m",
                "strawberry",
                "schema-codegen",
                str(pruned_path),
                "-o",
                str(tmp_schema),
            ],
        )
        _patch_schema_module(tmp_schema)

        # strawberry codegen reads from disk, so hand it the fragment-inlined
        # documents rather than the sources, which reference shared fragments.
        composed_dir = Path(tmp) / "operations"
        composed_dir.mkdir()
        composed_paths = []
        for name, text in composed:
            target = composed_dir / name
            target.write_text(text)
            composed_paths.append(str(target))

        generated_out.mkdir(parents=True, exist_ok=True)
        _run(
            [
                sys.executable,
                "-m",
                "strawberry",
                "codegen",
                "--schema",
                "_linear_schema:schema",
                "--app-dir",
                str(REPO_ROOT),
                "-p",
                "scripts.pydantic_plugin:PydanticPlugin",
                "-o",
                str(generated_out),
                *composed_paths,
            ],
            extra_path=Path(tmp),
        )

        # Ship the schema module with the package for the [strawberry] extra.
        schema_out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(tmp_schema, schema_out)

    # Drop modules from operations that no longer exist, so --check does not pass
    # on an orphan left over from a rename.
    expected = {Path(name).stem for name, _ in composed} | {"__init__", "fragments"}
    for orphan in generated_out.glob("*.py"):
        if orphan.stem not in expected:
            orphan.unlink()
            print(f"  removed orphan module: {orphan.name}")

    hoisted = _hoist_fragments(generated_out, set(fragments))
    if hoisted:
        print(f"  hoisted {len(hoisted)} shared fragment type(s) into fragments.py")

    init = generated_out / "__init__.py"
    modules = _embed_documents(generated_out, composed)
    init.write_text(
        GENERATED_HEADER
        + '"""Pydantic models generated from Linear\'s GraphQL schema."""\n',
    )
    print(f"  generated {len(modules)} operation module(s): {', '.join(modules)}")

    _ruff_format([schema_out, *sorted(generated_out.glob("*.py"))])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a temp dir and fail if the committed output differs",
    )
    args = parser.parse_args()

    if not args.check:
        generate(SCHEMA_MODULE, GENERATED_DIR)
        print("done")
        return

    with tempfile.TemporaryDirectory() as tmp:
        tmp_schema = Path(tmp) / "_schema.py"
        tmp_generated = Path(tmp) / "_generated"
        generate(tmp_schema, tmp_generated)

        stale: list[str] = []
        if not SCHEMA_MODULE.exists() or not filecmp.cmp(
            tmp_schema,
            SCHEMA_MODULE,
            shallow=False,
        ):
            stale.append(str(SCHEMA_MODULE.relative_to(REPO_ROOT)))
        expected = {p.name for p in tmp_generated.glob("*.py")}
        actual = {p.name for p in GENERATED_DIR.glob("*.py")}
        stale.extend(sorted(expected ^ actual))
        for name in sorted(expected & actual):
            if not filecmp.cmp(
                tmp_generated / name,
                GENERATED_DIR / name,
                shallow=False,
            ):
                import difflib

                with (
                    (tmp_generated / name).open() as f1,
                    (GENERATED_DIR / name).open() as f2,
                ):
                    diff = "".join(
                        difflib.unified_diff(
                            f1.readlines(),
                            f2.readlines(),
                            fromfile="tmp",
                            tofile="committed",
                        ),
                    )
                print(f"Diff for {name}:\n{diff}")
                stale.append(f"gtm_linear/_generated/{name}")

        if stale:
            msg = (
                "generated code is out of date:\n"
                + "\n".join(f"    {s}" for s in stale)
                + "\nrun: uv run python scripts/codegen.py"
            )
            raise SystemExit(msg)
        print("generated code is up to date")


if __name__ == "__main__":
    main()
