"""Generate operations/*.graphql from operations/_spec.toml and Linear's schema.

The operation documents used to be hand-written, which put the same class of drift
one level up from the types: a selection set could silently reference a field Linear
no longer has, or nest a payload wrapper incorrectly, and nothing would notice until
a request failed.

Everything structural is now derived from the schema:

  * whether a root field returns a bare entity, a mutation payload, or a connection,
    and therefore how deep the entity sits (``issueCreate { issue { ... } }``,
    ``issues { nodes { ... } }``) — found by searching the return type for the
    fragment's target type rather than being spelled out;
  * ``pageInfo`` on anything that paginates;
  * ``success`` on mutation payloads;
  * every field's existence and deprecation status.

What the spec chooses is which entities to project and how much of each — a payload
size decision the schema cannot make. Even then, named fields are checked against the
schema, so the spec cannot drift silently either.

Usage:
    uv run python scripts/gen_operations.py            # regenerate
    uv run python scripts/gen_operations.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path
from typing import Any

from graphql import (
    GraphQLEnumType,
    GraphQLInterfaceType,
    GraphQLList,
    GraphQLNonNull,
    GraphQLObjectType,
    GraphQLScalarType,
    build_schema,
)

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
SCHEMA_FILE = REPO_ROOT / "schema" / "linear.graphql"
OPERATIONS_DIR = REPO_ROOT / "operations"
SPEC_FILE = OPERATIONS_DIR / "_spec.toml"
FRAGMENTS_FILE = OPERATIONS_DIR / "_fragments.graphql"

GENERATED_NOTE = (
    "# Generated by scripts/gen_operations.py from operations/_spec.toml.\n"
    "# Do not edit by hand: edit the spec and regenerate.\n"
)

MAX_STRUCTURAL_DEPTH = 4


def _unwrap(type_: Any) -> Any:  # noqa: ANN401
    while isinstance(type_, (GraphQLNonNull, GraphQLList)):
        type_ = type_.of_type
    return type_


def _is_leaf(type_: Any) -> bool:  # noqa: ANN401
    return isinstance(_unwrap(type_), (GraphQLScalarType, GraphQLEnumType))


def _selectable(field: Any) -> bool:  # noqa: ANN401
    """A field we can select without supplying arguments."""
    return not any(isinstance(a.type, GraphQLNonNull) for a in field.args.values())


def _leaf_fields(type_: Any, exclude: set[str]) -> list[str]:  # noqa: ANN401
    return sorted(
        name
        for name, field in type_.fields.items()
        if _is_leaf(field.type)
        and not field.deprecation_reason
        and _selectable(field)
        and name not in exclude
    )


def _resolve_fields(
    type_: Any,  # noqa: ANN401
    spec_fields: Any,  # noqa: ANN401
    exclude: set[str],
    where: str,
) -> list[str]:
    """Validate a spec's field list against the schema, or take every leaf."""
    if spec_fields == "all":
        return _leaf_fields(type_, exclude)

    missing = [f for f in spec_fields if f not in type_.fields]
    if missing:
        msg = f"{where}: {type_.name} has no field(s) {', '.join(missing)}"
        raise SystemExit(msg)
    deprecated = [f for f in spec_fields if type_.fields[f].deprecation_reason]
    if deprecated:
        print(
            f"  warning: {where} selects deprecated field(s): {', '.join(deprecated)}"
        )
    return list(spec_fields)


def _render_fragment(name: str, spec: dict[str, Any], schema: Any) -> str:  # noqa: ANN401
    type_name = spec["on"]
    type_ = schema.get_type(type_name)
    if not isinstance(type_, (GraphQLObjectType, GraphQLInterfaceType)):
        msg = f"fragment {name}: unknown type {type_name}"
        raise SystemExit(msg)

    expand: dict[str, Any] = spec.get("expand", {})
    exclude = set(spec.get("exclude", []))
    lines = [f"fragment {name} on {type_name} {{"]

    for field_name in _resolve_fields(
        type_, spec["fields"], exclude, f"fragment {name}"
    ):
        lines.append(f"  {field_name}")

    for field_name, nested_fields in expand.items():
        if field_name not in type_.fields:
            msg = f"fragment {name}: {type_name} has no field {field_name}"
            raise SystemExit(msg)
        nested_type = _unwrap(type_.fields[field_name].type)
        resolved = _resolve_fields(
            nested_type,
            nested_fields,
            set(),
            f"fragment {name}.{field_name}",
        )
        lines.append(f"  {field_name} {{")
        lines.extend(f"    {f}" for f in resolved)
        lines.append("  }")

    lines.append("}")
    return "\n".join(lines)


def _path_to_type(
    root_type: Any,  # noqa: ANN401
    target: str,
    depth: int = 0,
) -> list[str] | None:
    """Find the field path from a root field's return type down to `target`.

    This is what removes the hand-written knowledge of Linear's response shapes:
    ``issueCreate`` wraps its entity in ``issue``, ``issues`` wraps in ``nodes``,
    ``issue`` wraps in nothing, and the walk discovers each.
    """
    root_type = _unwrap(root_type)
    if getattr(root_type, "name", None) == target:
        return []
    if depth >= MAX_STRUCTURAL_DEPTH or not isinstance(root_type, GraphQLObjectType):
        return None

    # Relay connections expose both `nodes` and `edges { node }`. Both reach the
    # entity; `nodes` is one level shallower, so prefer it and fall back to `edges`
    # only if a connection omits `nodes`.
    def preference(field_name: str) -> tuple[int, str]:
        if field_name == "nodes":
            return (0, field_name)
        if field_name == "edges":
            return (2, field_name)
        return (1, field_name)

    for field_name in sorted(root_type.fields, key=preference):
        nested = _unwrap(root_type.fields[field_name].type)
        if not isinstance(nested, GraphQLObjectType):
            continue
        sub = _path_to_type(nested, target, depth + 1)
        if sub is not None:
            return [field_name, *sub]
    return None


def _render_operation(
    name: str,
    spec: dict[str, Any],
    schema: Any,  # noqa: ANN401
    fragments: dict[str, dict[str, Any]],
) -> str:
    kind = spec["kind"]
    root_name = spec["root"]
    root_holder = schema.query_type if kind == "query" else schema.mutation_type
    if root_name not in root_holder.fields:
        msg = f"operation {name}: {kind} has no root field {root_name}"
        raise SystemExit(msg)
    root_field = root_holder.fields[root_name]

    variables: dict[str, str] = spec.get("variables", {})
    arguments: dict[str, str] = spec.get("arguments", {})
    for arg_name in arguments:
        if arg_name not in root_field.args:
            msg = f"operation {name}: {root_name} has no argument {arg_name}"
            raise SystemExit(msg)

    header = f"{kind} {name}"
    if variables:
        rendered = ", ".join(f"${var}: {gql}" for var, gql in variables.items())
        header += f"({rendered})"

    call = root_name
    if arguments:
        rendered = ", ".join(f"{a}: {v}" for a, v in arguments.items())
        call += f"({rendered})"

    return_type = _unwrap(root_field.type)
    fragment_name = spec.get("fragment")

    if fragment_name is None:
        # No entity projection: a bare payload, e.g. issueDelete { success }.
        leaves = _leaf_fields(return_type, set())
        selection = ["success"] if "success" in leaves else leaves
        body = list(selection)
    else:
        target = fragments[fragment_name]["on"]
        path = _path_to_type(return_type, target)
        if path is None:
            msg = (
                f"operation {name}: cannot reach {target} from "
                f"{return_type.name}; is the fragment right for this root field?"
            )
            raise SystemExit(msg)
        body = _render_selection(return_type, path, fragment_name, spec)

    lines = [
        f"{header} {{",
        f"  {call} {{",
        *[f"    {line}" for line in body],
        "  }",
        "}",
    ]
    return "\n".join(lines)


def _render_selection(
    return_type: Any,  # noqa: ANN401
    path: list[str],
    fragment_name: str,
    spec: dict[str, Any],
) -> list[str]:
    """Render the nested selection down to the fragment, adding pageInfo en route.

    ``pageInfo`` is emitted at every level whose type declares one, so a connection
    picks up its cursor metadata without the spec having to say so.
    """
    paginate = spec.get("paginated", True)
    lines: list[str] = []
    indent = 0

    cursor = return_type
    if "success" in getattr(cursor, "fields", {}):
        lines.append("success")

    stack: list[Any] = []
    for step in path:
        lines.append(f"{' ' * indent}{step} {{")
        stack.append(cursor)
        cursor = _unwrap(cursor.fields[step].type)
        indent += 2

    lines.append(f"{' ' * indent}...{fragment_name}")

    for parent in reversed(stack):
        indent -= 2
        lines.append(f"{' ' * indent}}}")
        if paginate and "pageInfo" in getattr(parent, "fields", {}):
            lines.append(f"{' ' * indent}pageInfo {{")
            lines.append(f"{' ' * (indent + 2)}...PageInfoFields")
            lines.append(f"{' ' * indent}}}")

    return lines


def generate(out_dir: Path) -> list[str]:
    spec = tomllib.loads(SPEC_FILE.read_text())
    schema = build_schema(SCHEMA_FILE.read_text())
    fragments: dict[str, dict[str, Any]] = spec["fragments"]

    rendered_fragments = [
        _render_fragment(name, frag, schema) for name, frag in fragments.items()
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "_fragments.graphql").write_text(
        GENERATED_NOTE + "\n" + "\n\n".join(rendered_fragments) + "\n",
    )

    written = ["_fragments.graphql"]
    for name, op in spec["operations"].items():
        text = _render_operation(name, op, schema, fragments)
        (out_dir / f"{name}.graphql").write_text(f"{text}\n")
        written.append(f"{name}.graphql")

    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()

    if not args.check:
        written = generate(OPERATIONS_DIR)
        print(f"wrote {len(written)} file(s) to operations/")
        return

    import filecmp
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        written = generate(tmp_dir)
        stale = [
            name
            for name in written
            if not (OPERATIONS_DIR / name).exists()
            or not filecmp.cmp(tmp_dir / name, OPERATIONS_DIR / name, shallow=False)
        ]
        if stale:
            msg = (
                "operations are out of date:\n"
                + "\n".join(f"    {s}" for s in stale)
                + "\nrun: uv run python scripts/gen_operations.py"
            )
            raise SystemExit(msg)
        print("operations are up to date")


if __name__ == "__main__":
    main()
